config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/secret', to: 'pages#secret', as: :secret
  root to: 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :zxcvbnable

  def send_devise_notification(notification, *args)
    if Rails.env.production?
      # No worker process in production to handle scheduled tasks
      devise_mailer.send(notification, self, *args).deliver_now
    else
      devise_mailer.send(notification, self, *args).deliver_later
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Tienda</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Tienda', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <% if user_signed_in? %>
            <li><%= link_to 'Secret', secret_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Profile', edit_user_registration_path %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
  <% end %>
</div>

<%= yield :top_content %>

<div class="container">
  <h1><%= yield :header %></h1>

  <%= yield %>
</div>

<div id="footer">
  <div class="container">
    <p class="text-muted">Created by <a href="http://radiant-wind.com" target="_blank">Edu</a></p>
  </div>
</div>

</body>
</html>

app/views/pages/index.html.erb
<% content_for :top_content do %>
<div class="jumbotron">
    <div class="container">
        <h1>Welcome!</h1>
        <p>Register to get started.</p>
        <p>
            <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
        </p>
    </div>
</div>
<% end %>

app/views/pages/secret.html.erb
<% header "Secret!" %>